import { PERFIL, SPRITES } from "../constants/images";

export const PERSONAGENS_DATA = [
  {
    id: 1,
    nome: "Ayla",
    sprite: SPRITES.AYLA_SPRITE,
    perfil: PERFIL.AYLA_PERFIL,
    perfilCor: "perfil-amarelo",
    level: 10,
    pvAtual: 20,
    pvTotal: 20,
    pmAtual: 1,
    pmTotal: 5,
    atributos: {
      forca: 1,
      destreza: 100,
      constituicao: 1,
      inteligencia: 1,
    },
    acoes: {
      ataques: [1],
      habilidades: [1],
    },
  },
  {
    id: 2,
    nome: "Andy",
    sprite: SPRITES.ANDY_SPRITE,
    perfil: PERFIL.ANDY_PERFIL,
    perfilCor: "perfil-verde",
    level: 10,
    pvAtual: 20,
    pvTotal: 20,
    pmAtual: 5,
    pmTotal: 5,
    atributos: {
      forca: 1,
      destreza: 1,
      constituicao: 1,
      inteligencia: 1,
    },
    acoes: {
      ataques: [1],
      habilidades: [1],
    },
  },
  {
    id: 3,
    nome: "Dominick",
    sprite: SPRITES.DOMINICK_SPRITE,
    perfil: PERFIL.DOMINICK_PERFIL,
    perfilCor: "perfil-roxo",
    level: 10,
    pvAtual: 20,
    pvTotal: 20,
    pmAtual: 5,
    pmTotal: 5,
    atributos: {
      forca: 1,
      destreza: 1,
      constituicao: 1,
      inteligencia: 1,
    },
    acoes: {
      ataques: [1],
      habilidades: [1],
    },
  },
  {
    id: 4,
    nome: "Aphelios",
    sprite: SPRITES.APHELIOS_SPRITE,
    perfil: PERFIL.APHELIOS_PERFIL,
    perfilCor: "perfil-ciano",
    level: 10,
    pvAtual: 20,
    pvTotal: 20,
    pmAtual: 5,
    pmTotal: 5,
    atributos: {
      forca: 1,
      destreza: 1,
      constituicao: 1,
      inteligencia: 1,
    },
    acoes: {
      ataques: [1],
      habilidades: [1],
    },
  },
  {
    id: 5,
    nome: "Lobo",
    sprite: SPRITES.LOBO_SPRITE,
    perfil: PERFIL.LOBO_PERFIL,
    perfilCor: "perfil-inimigo",
    level: 2,
    pvAtual: 2,
    pvTotal: 10,
    pmAtual: 2,
    pmTotal: 2,
    atributos: {
      forca: 1,
      destreza: 1,
      constituicao: 1,
      inteligencia: 1,
    },
    acoes: {
      ataques: [2],
    },
  },
];
